# Generated by Django 5.0.7 on 2024-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
