# Generated by Django 5.0.7 on 2024-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_product_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='users/'),
            preserve_default=False,
        ),
    ]
