# Generated by Django 5.0.7 on 2024-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
