# Generated by Django 5.0.7 on 2024-08-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_order_is_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing for Dispatch'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('no_answer', 'No Answer'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
