# Generated by Django 5.0.7 on 2024-08-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_stream',
        ),
        migrations.AddField(
            model_name='order',
            name='stream',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apps.stream'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('deliver', 'Deliver'), ('delivered', 'Delivered'), ('cant_phone', 'Cant_phone'), ('canceled', 'Canceled'), ('archived', 'Archived')], default='new', max_length=50),
        ),
    ]
